name: Structure & Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23
        with:
          globs: "**/*.md"

  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Check Folder Structure
        run: |
          if [ ! -d "1_Evening 1 The Importance of Modeling" ]; then echo "Missing Evening 1"; exit 1; fi
          if [ ! -d "2_Evening 2 Diagram Overview" ]; then echo "Missing Evening 2"; exit 1; fi
          echo "Structure Validated"
